In [3]:
import numpy as np
import pandas as pd

In [5]:
data = pd.read_csv('titanic.csv')
data.head(5)

  Cabin            Ticket number  Survived
0   NaN         A/5 21171      5         0
1   C85          PC 17599      3         1
2   NaN  STON/O2. 3101282      6         1
3  C123            113803      3         1
4   NaN            373450      A         0

In [6]:
data['number'].unique()

<StringArray>
['5', '3', '6', 'A', '2', '1', '4']
Length: 7, dtype: str

In [ ]:
# wherever you have any numerical and categorical column in same colum, create a new column for Numeric & Categoric data
# Extract Numeric Column
data['number_numeric'] = pd.to_numeric(data['number'], errors='coerce', downcast='integer')

In [9]:
# Extract Categorical Column
data['categorical_column'] = np.where(data['number_numeric'].isnull(), data['number'], np.nan)
data.head(5)

  Cabin            Ticket number  Survived  number_numeric categorical_column
0   NaN         A/5 21171      5         0             5.0                NaN
1   C85          PC 17599      3         1             3.0                NaN
2   NaN  STON/O2. 3101282      6         1             6.0                NaN
3  C123            113803      3         1             3.0                NaN
4   NaN            373450      A         0             NaN                  A

In [10]:
# Extracting categories for Cabin Column
data['cabin_num'] = data['Cabin'].str.extract('(\d+)') # It captures numerical part
data['cabin_cat'] = data['Cabin'].str[0]
data.head(5)

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_7389/813130335.py:2: SyntaxWarning: invalid escape sequence '\d'
  data['cabin_num'] = data['Cabin'].str.extract('(\d+)') # It captures numerical part

,Cabin,Ticket,number,Survived,number_numeric,categorical_column,cabin_num,cabin_cat
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,85,C
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN
3,C123,113803,3,1,3.0,NaN,123,C
4,NaN,373450,A,0,NaN,A,NaN,NaN

In [12]:
# Extracting  categories for Ticket Column
data['ticket_num'] = data['Ticket'].apply(lambda s : s.split()[-1])
data['ticket_num'] = pd.to_numeric(data['ticket_num'], errors='coerce', downcast='integer')

data['ticket_cat'] = data['Ticket'].apply(lambda s : s.split()[0])
data['ticket_cat'] = np.where(data['ticket_cat'].str.isdigit(), np.nan, data['ticket_cat'])

data.head(5)

,Cabin,Ticket,number,Survived,number_numeric,categorical_column,cabin_num,cabin_cat,ticket_num,ticket_cat
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN,21171.0,A/5
1,C85,PC 17599,3,1,3.0,NaN,85,C,17599.0,PC
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN,3101282.0,STON/O2.
3,C123,113803,3,1,3.0,NaN,123,C,113803.0,NaN
4,NaN,373450,A,0,NaN,A,NaN,NaN,373450.0,NaN