In [1]:
print("working")

working

In [10]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [11]:
data = pd.read_csv('ds.csv');
data.head(4)

   size  bedrooms  age   price
0  1000         2   20  200000
1  1200         2   15  230000
2  1400         3   12  270000
3  1500         3   10  290000

In [12]:
x = data[["size", "bedrooms", "age"]]
y = data["price"]

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=42)
X_train

   size  bedrooms  age
5  1700         3    7
0  1000         2   20
7  1900         4    5
2  1400         3   12
9  2200         5    3
4  1600         3    8
3  1500         3   10
6  1800         4    6

In [14]:
model = LinearRegression()

model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

In [23]:
r2 = r2_score(y_pred, Y_test)
print(r2 * 100)

99.89157140325031